### ISSUE TITLE
Hibernated System

### ISSUE THREAD

**Issue by DlieBG** [boba2fett/WinModify#1]
Your script doesn't work, when you run a hibernated file system.

**Comment by DlieBG** [comment]
Can you please resolve this issue?!

**Comment by boba2fett** [comment]
Unfortunately, there are problems related to it. I will keep this in mind when this project is revived, but for the near future there are plans.
I appreciate any further investigation and would be happy to merge a fix!

**Comment by DlieBG** [comment]
Ok, thank you for nothing and wasting my time!
